import { RiskRule } from './types';

export const defaultRules: RiskRule[] = [
  // Health & Temperature
  {
    id: 'extreme-heat',
    name: 'Extreme Heat Warning',
    signal: 'temperature',
    operator: '>',
    threshold: 40,
    severity: 'critical',
    message: 'Extreme heat conditions. Risk of heatstroke is high. Avoid outdoor activities.',
    category: 'health',
  },
  {
    id: 'high-heat',
    name: 'High Heat Advisory',
    signal: 'temperature',
    operator: '>',
    threshold: 35,
    severity: 'warning',
    message: 'High temperatures detected. Stay hydrated and limit prolonged outdoor exposure.',
    category: 'health',
  },
  {
    id: 'extreme-cold',
    name: 'Extreme Cold Warning',
    signal: 'temperature',
    operator: '<',
    threshold: -10,
    severity: 'critical',
    message: 'Extreme cold conditions. High risk of frostbite and hypothermia.',
    category: 'health',
  },
  {
    id: 'freezing',
    name: 'Freezing Conditions',
    signal: 'temperature',
    operator: '<',
    threshold: 0,
    severity: 'warning',
    message: 'Temperatures are below freezing. Watch for ice on roads and walkways.',
    category: 'travel',
  },

  // Wind & Aviation
  {
    id: 'storm-force-wind',
    name: 'Storm-Force Wind Warning',
    signal: 'wind_speed',
    operator: '>',
    threshold: 90,
    severity: 'critical',
    message: 'Storm-force winds detected. Severe risk to aviation and structures.',
    category: 'aviation',
  },
  {
    id: 'high-wind',
    name: 'High Wind Warning',
    signal: 'wind_speed',
    operator: '>',
    threshold: 50,
    severity: 'warning',
    message: 'High wind speeds may affect outdoor activities and light aviation.',
    category: 'aviation',
  },
  {
    id: 'strong-wind',
    name: 'Strong Wind Advisory',
    signal: 'wind_speed',
    operator: '>',
    threshold: 30,
    severity: 'info',
    message: 'Breezy conditions. Secure loose outdoor objects.',
    category: 'outdoor',
  },

  // Precipitation & Travel
  {
    id: 'torrential-rain',
    name: 'Torrential Rain Warning',
    signal: 'rainfall_1h',
    operator: '>',
    threshold: 30,
    severity: 'danger',
    message: 'Torrential rainfall detected. High risk of flash flooding and severe travel disruption.',
    category: 'travel',
  },
  {
    id: 'heavy-rain',
    name: 'Heavy Rain Advisory',
    signal: 'rainfall_1h',
    operator: '>',
    threshold: 10,
    severity: 'warning',
    message: 'Heavy rain detected. Expect localized flooding and poor driving conditions.',
    category: 'travel',
  },
  {
    id: 'heavy-snowfall',
    name: 'Heavy Snowfall Warning',
    signal: 'snowfall_1h',
    operator: '>',
    threshold: 5,
    severity: 'warning',
    message: 'Heavy snowfall detected. Travel conditions may be hazardous.',
    category: 'travel',
  },

  // Visibility
  {
    id: 'low-visibility',
    name: 'Low Visibility Warning',
    signal: 'visibility',
    operator: '<',
    threshold: 1,
    severity: 'danger',
    message: 'Visibility is extremely poor (<1km). Severe travel and aviation disruptions likely.',
    category: 'aviation',
  },
  {
    id: 'poor-visibility',
    name: 'Poor Visibility Advisory',
    signal: 'visibility',
    operator: '<',
    threshold: 5,
    severity: 'warning',
    message: 'Visibility is reduced (<5km). Exercise caution while traveling.',
    category: 'travel',
  },

  // Other specific conditions
  {
    id: 'very-high-humidity',
    name: 'Very High Humidity',
    signal: 'humidity',
    operator: '>',
    threshold: 90,
    severity: 'info',
    message: 'Extremely humid conditions. May increase the perceived temperature (feels like).',
    category: 'health',
  },
  {
    id: 'dangerous-air-quality',
    name: 'Dangerous Air Quality Warning',
    signal: 'air_quality_index',
    operator: '>=',
    threshold: 4, // 4 = Poor, 5 = Very Poor
    severity: 'danger',
    message: 'Air quality is very poor. Stay indoors and keep windows closed.',
    category: 'health',
  },
  {
    id: 'poor-air-quality',
    name: 'Poor Air Quality Advisory',
    signal: 'air_quality_index',
    operator: '>=',
    threshold: 3, // 3 = Moderate
    severity: 'warning',
    message: 'Air quality is moderate to poor. Sensitive groups should limit outdoor exertion.',
    category: 'health',
  },
  {
    id: 'low-pressure-system',
    name: 'Low Pressure System',
    signal: 'pressure',
    operator: '<',
    threshold: 980,
    severity: 'info',
    message: 'A significant low-pressure system is present, often associated with stormy weather.',
    category: 'aviation',
  }
];
